### ISSUE TITLE
Show a graph with data

### ISSUE THREAD

**Issue by DKalachniuk** [hungrxyz/Infected#2]
Hi there, thanks for the app!

It would be nice to show a graph in the app so We would be able to see how the infections are going. Now we see the comparison with yesterday but will be cool to see the graph as well 
Let's say for last 7/14/30 days

**Comment by markotect** [comment]
Hi @DKalachniuk, glad you like the app.

I'm not spending a lot of time on this app anymore and graphs would be a big thing to add at this point so I'm not planning on adding it. Next time 😉. However feel free to open a pull request if you feel like adding them.
